### ISSUE TITLE
native-echarts uses webview from react native core

### ISSUE THREAD

**Issue by ha-younes72** [biill/StackthonProject#9]
The package is not showing a chart because the native-echarts uses webview from react-native while the package moved to react-native-webview. It may be convenient to use react-native-echarts-wrapper which updated this import.

**Comment by biill** [comment]
I will take of look of that and make the update, thanks!

**Comment by harshnagalla** [comment]
Is this issue solved? Seems like this issue still presists in the native-echarts project

**Comment by biill** [comment]
I this I got it fixed in last PR, please let me know if is not working.

Best regards，

Shan tang

**Comment by harshnagalla** [comment]
I am still getting this error that Webview has been moved from react-native to react-native-webview. Can you help check?

**Comment by biill** [comment]
Ok, will do it after work today, thanks for letting me know

Best regards，

Shan tang

**Comment by harshnagalla** [comment]
Great! Thanks!

**Comment by harshnagalla** [comment]
Were you able to fix it?

**Comment by biill** [comment]
So, currently this is not the issue, the really issue is from expo, I have listed issue link here, and it's still an open issue from expo:

https://github.com/expo/web-examples/issues/73

I will see if I can find way to solve this issue, will keep you posted

**Comment by biill** [comment]
Webview issue is fixed, but currently there is expo issue I'm experiencing.
